# Include the drivers you want enabled
DRIVERS = -DINCLUDE_SDRAM_DRIVER \
		  -DINCLUDE_LCD_CTRL_DRIVER \
		  -DINCLUDE_DMA2D_DRIVER \
		  -DINCLUDE_FONT_TABLE \
		  -DINCLUDE_GRAPHICS_MODULE \
		  -DINCLUDE_USART_DRIVER
